version: '3.3'
services:
  postgress:
    image: postgres:alpine
    container_name: postgres
    environment:
        - POSTGRES_USER=adminx
        - POSTGRES_PASSWORD=passx
        - POSTGRES_DB=dbx
    ports:
        - "5432:5432"
    volumes: 
        - ./db_postgres:/var/lib/postgresql/data
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
        - "6379:6379"
    volumes: 
        - ./db_redis:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: always